swagger: "2.0"
info:
  version: "0.0.2"
  title: SmartDocs HTML bulk export
# during dev, should point to your local machine
host: localhost:10010
# basePath prefixes all resource paths 
basePath: /
# 
schemes:
  # tip: remove http to make production-grade
  - http
  - https
# format of bodies a client can send (Content-Type)
securityDefinitions:
  basic:
    type: basic
consumes:
  - application/json
# format of the responses to the client (Accepts)
produces:
  - text/html
paths:
  /o/{org}/apimodels/{model}/download:
    # binds a127 app logic to a route
    x-swagger-router-controller: download
    get:
      description: For a given org and model, download a zip of their SmartDocs
      # used as the method name of the controller
      operationId: download
      produces:
        - application/zip
      #  - application/octet-stream
      parameters:
        - name: model
          in: path
          description: The name of the API model
          required: true
          type: string
        - name: org
          in: path
          description: The name of the organization
          required: true
          type: string
      responses:
        "200":
          description: Success
          schema:
            type: string
            # a pointer to a definition
            #$ref: "#/definitions/Zip"
        # responses may fall through to errors
        default:
          description: Error
          schema:
            $ref: "#/definitions/ErrorResponse"
# complex objects have schema definitions
definitions:
  ErrorResponse:
    required:
      - message
    properties:
      message:
        type: string
